version: '3'
services:
  api:
    container_name: 'api'
    image: golang:1.13.1
    command: "bash"
    stdin_open: true
    tty: true
    volumes:
      - './api:/go/src/api'
    ports:
      - '8181:8080'
    networks:
      - backend
    working_dir: '/go/src/api'
networks:
  backend:
